# Generated by Django 6.0.2 on 2026-02-08 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='記事タイトル')),
                ('article_path', models.TextField(help_text='記事の内容と記事内のメディアはそこに保存される', verbose_name='記事実態の保存先パス')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256, verbose_name='ユーザー名')),
                ('code', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='ユーザーユニークコード')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='グループ名')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='defaultdb.group', verbose_name='親グループ')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, verbose_name='イベント名')),
                ('type', models.CharField(choices=[('OFFCIAL', '公式'), ('CLIENT', '企業'), ('GROUP', 'グループ')], default='OFFCIAL', max_length=16, verbose_name='キャンペーンタイプ')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='イベント概要')),
                ('start_at', models.DateTimeField(verbose_name='イベント開始日時')),
                ('end_at', models.DateTimeField(verbose_name='イベント終了日時')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='defaultdb.group', verbose_name='対象グループ')),
            ],
            options={
                'db_table': 'campaign',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='タグ名')),
                ('is_official', models.BooleanField(default=False, verbose_name='公式タグフラグ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.user')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='GroupUserRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.user')),
            ],
            options={
                'db_table': 'group_user_relation',
            },
        ),
        migrations.CreateModel(
            name='ArticleTagRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.tag')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.user', verbose_name='タグの付与者')),
            ],
            options={
                'db_table': 'article_tag_relation',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.user', verbose_name='記事の作成者'),
        ),
        migrations.CreateModel(
            name='UserTagRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.user')),
            ],
            options={
                'db_table': 'user_tag_relation',
            },
        ),
        migrations.CreateModel(
            name='ArticleCampaignRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.article')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.campaign')),
            ],
            options={
                'db_table': 'article_campaign_relation',
                'constraints': [models.UniqueConstraint(fields=('article',), name='article_campaign_article_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('name',), name='group_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gte', models.F('start_at'))), name='campaign_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('type', 'OFFCIAL')), models.Q(('group__isnull', False), ('type__in', ('CLIENT', 'GROUP'))), _connector='OR'), name='campaign_type_group_valid'),
        ),
        migrations.AddConstraint(
            model_name='articletagrelation',
            constraint=models.UniqueConstraint(fields=('article', 'tag'), name='article_and_tag_uniq'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='article_title_and_user_uniq'),
        ),
        migrations.AddIndex(
            model_name='usertagrelation',
            index=models.Index(fields=['user', 'tag'], name='user_tag_re_user_id_5d706d_idx'),
        ),
        migrations.AddConstraint(
            model_name='usertagrelation',
            constraint=models.UniqueConstraint(fields=('user', 'tag'), name='user_and_tag_uniq'),
        ),
    ]
